runtime: python39  # Chạy Python 3.9 trên GAE
entrypoint: gunicorn -b :$PORT app:app  # Gunicorn để chạy ứng dụng Flask
instance_class: F2  # Thực thi với F2 instance class
env_variables:
  FLASK_ENV: 'production'
